workflows:
  ios-workflow:
    name: iOS Workflow (Requires Apple Developer Account)
    max_build_duration: 120
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: codemagic
    environment:
      ios_signing:
        distribution_type: development
        bundle_identifier: com.alkhatm.app
      vars:
        BUNDLE_ID: "com.alkhatm.app"
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        FLUTTER_BUILD_MODE: debug
        FLUTTER_BUILD_NAME: "1.0.0"
        FLUTTER_BUILD_NUMBER: "1"
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up iOS build
        script: |
          echo "Building iOS app with proper code signing"
          
      - name: Get Flutter packages
        script: |
          flutter pub get
          
      - name: Install CocoaPods
        script: |
          cd ios
          pod install
          cd ..
          
      - name: Build iOS IPA
        script: |
          flutter build ipa --release \
            --build-name=1.0.0 \
            --build-number=$BUILD_NUMBER
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - phrtool000@gmail.com
        notify:
          success: true
          failure: true
      app_store_connect:
        auth: integration
        submit_to_testflight: false
        submit_to_app_store: false
        
  android-workflow:
    name: Android Workflow
    max_build_duration: 120
    instance_type: linux_x2
    environment:
      vars:
        PACKAGE_NAME: "com.alkhatm.app"
      flutter: stable
      java: 17
    scripts:
      - name: Get Flutter packages
        script: |
          flutter packages pub get
          
      - name: Flutter analyze
        script: |
          flutter analyze
          
      - name: Build APK
        script: |
          flutter build apk --release --build-name=1.0.0 --build-number=$BUILD_NUMBER
          
      - name: Build App Bundle
        script: |
          flutter build appbundle --release --build-name=1.0.0 --build-number=$BUILD_NUMBER
    artifacts:
      - build/app/outputs/**/*.apk
      - build/app/outputs/**/*.aab
      - build/**/outputs/**/*.json
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - YOUR_EMAIL@example.com # Replace with your email
        notify:
          success: true
          failure: true
      # Uncomment below when ready for Google Play
      # google_play:
      #   credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
      #   track: internal
      #   submit_as_draft: true
