workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: codemagic
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.alkhatm.app
      vars:
        BUNDLE_ID: "com.alkhatm.app"
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        APP_STORE_CONNECT_ISSUER_ID: Encrypted(...)
        APP_STORE_CONNECT_KEY_IDENTIFIER: Encrypted(...)
        APP_STORE_CONNECT_PRIVATE_KEY: Encrypted(...)
        CERTIFICATE_PRIVATE_KEY: Encrypted(...)
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up code signing settings
        script: |
          # Set up provisioning profiles
          echo "Setting up iOS code signing..."
          
      - name: Get Flutter packages
        script: |
          flutter pub get
          
      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install
          cd ..
          
      - name: Flutter build iOS (no-codesign for debugging)
        script: |
          flutter build ios --release \
            --no-codesign \
            --build-name=1.0.0 \
            --build-number=$BUILD_NUMBER
            
      - name: Build iOS IPA
        script: |
          xcode-project build-ipa \
            --workspace ios/Runner.xcworkspace \
            --scheme Runner \
            --archive-flags="-destination 'generic/platform=iOS'"
            
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - web.brain.devlop@gmail.com
          - phrtool000@gmail.com
        notify:
          success: true
          failure: true
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: false
