workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      vars:
        BUNDLE_ID: "com.alkhatm.app"
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up key properties
        script: |
          echo "Setting up iOS build environment..."
          
      - name: Get Flutter packages
        script: |
          flutter packages pub get
          
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
          
      - name: Flutter analyze
        script: |
          flutter analyze
          
      - name: Flutter build iOS
        script: |
          flutter build ios --debug --no-codesign
    artifacts:
      - build/ios/iphoneos/Runner.app
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - phrtool000@gmail.com
        notify:
          success: true
          failure: true
        
  android-workflow:
    name: Android Workflow
    max_build_duration: 120
    instance_type: linux_x2
    environment:
      vars:
        PACKAGE_NAME: "com.alkhatm.app"
      flutter: stable
      java: 17
    scripts:
      - name: Get Flutter packages
        script: |
          flutter packages pub get
          
      - name: Flutter analyze
        script: |
          flutter analyze
          
      - name: Build APK
        script: |
          flutter build apk --release --build-name=1.0.0 --build-number=$BUILD_NUMBER
          
      - name: Build App Bundle
        script: |
          flutter build appbundle --release --build-name=1.0.0 --build-number=$BUILD_NUMBER
    artifacts:
      - build/app/outputs/**/*.apk
      - build/app/outputs/**/*.aab
      - build/**/outputs/**/*.json
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - YOUR_EMAIL@example.com # Replace with your email
        notify:
          success: true
          failure: true
      # Uncomment below when ready for Google Play
      # google_play:
      #   credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
      #   track: internal
      #   submit_as_draft: true
